//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTerraBot.Properties
{
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WildTerraBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string InspectLabelGuild
        {
            get
            {
                return ResourceManager.GetString("InspectLabelGuild", resourceCulture);
            }
        }

        internal static string InspectLabelAvatar
        {
            get
            {
                return ResourceManager.GetString("InspectLabelAvatar", resourceCulture);
            }
        }

        internal static string InspectLabelBorder
        {
            get
            {
                return ResourceManager.GetString("InspectLabelBorder", resourceCulture);
            }
        }

        internal static string InspectLabelCurrentSkill
        {
            get
            {
                return ResourceManager.GetString("InspectLabelCurrentSkill", resourceCulture);
            }
        }

        internal static string InspectLabelDistance
        {
            get
            {
                return ResourceManager.GetString("InspectLabelDistance", resourceCulture);
            }
        }

        internal static string InspectLabelGeneratedAt
        {
            get
            {
                return ResourceManager.GetString("InspectLabelGeneratedAt", resourceCulture);
            }
        }

        internal static string InspectLabelHp
        {
            get
            {
                return ResourceManager.GetString("InspectLabelHp", resourceCulture);
            }
        }

        internal static string InspectLabelLevel
        {
            get
            {
                return ResourceManager.GetString("InspectLabelLevel", resourceCulture);
            }
        }

        internal static string InspectLabelName
        {
            get
            {
                return ResourceManager.GetString("InspectLabelName", resourceCulture);
            }
        }

        internal static string InspectLabelPlayerFound
        {
            get
            {
                return ResourceManager.GetString("InspectLabelPlayerFound", resourceCulture);
            }
        }

        internal static string InspectLabelPosition
        {
            get
            {
                return ResourceManager.GetString("InspectLabelPosition", resourceCulture);
            }
        }

        internal static string InspectLabelQuery
        {
            get
            {
                return ResourceManager.GetString("InspectLabelQuery", resourceCulture);
            }
        }

        internal static string InspectLabelSex
        {
            get
            {
                return ResourceManager.GetString("InspectLabelSex", resourceCulture);
            }
        }

        internal static string InspectLabelSp
        {
            get
            {
                return ResourceManager.GetString("InspectLabelSp", resourceCulture);
            }
        }

        internal static string InspectLabelState
        {
            get
            {
                return ResourceManager.GetString("InspectLabelState", resourceCulture);
            }
        }

        internal static string InspectLabelTitleRaw
        {
            get
            {
                return ResourceManager.GetString("InspectLabelTitleRaw", resourceCulture);
            }
        }

        internal static string InspectLabelTitleLocalized
        {
            get
            {
                return ResourceManager.GetString("InspectLabelTitleLocalized", resourceCulture);
            }
        }

        internal static string InspectNoCosmeticsData
        {
            get
            {
                return ResourceManager.GetString("InspectNoCosmeticsData", resourceCulture);
            }
        }

        internal static string InspectNoEquipmentData
        {
            get
            {
                return ResourceManager.GetString("InspectNoEquipmentData", resourceCulture);
            }
        }

        internal static string InspectNoProfSkillsData
        {
            get
            {
                return ResourceManager.GetString("InspectNoProfSkillsData", resourceCulture);
            }
        }

        internal static string InspectNoSkillsData
        {
            get
            {
                return ResourceManager.GetString("InspectNoSkillsData", resourceCulture);
            }
        }

        internal static string InspectReportTitle
        {
            get
            {
                return ResourceManager.GetString("InspectReportTitle", resourceCulture);
            }
        }

        internal static string InspectSectionCosmetics
        {
            get
            {
                return ResourceManager.GetString("InspectSectionCosmetics", resourceCulture);
            }
        }

        internal static string InspectSectionEquipment
        {
            get
            {
                return ResourceManager.GetString("InspectSectionEquipment", resourceCulture);
            }
        }

        internal static string InspectSectionGeneral
        {
            get
            {
                return ResourceManager.GetString("InspectSectionGeneral", resourceCulture);
            }
        }

        internal static string InspectSectionAttributes
        {
            get
            {
                return ResourceManager.GetString("InspectSectionAttributes", resourceCulture);
            }
        }

        internal static string InspectSectionBuffs
        {
            get
            {
                return ResourceManager.GetString("InspectSectionBuffs", resourceCulture);
            }
        }

        internal static string InspectSectionEconomy
        {
            get
            {
                return ResourceManager.GetString("InspectSectionEconomy", resourceCulture);
            }
        }

        internal static string InspectSectionObservations
        {
            get
            {
                return ResourceManager.GetString("InspectSectionObservations", resourceCulture);
            }
        }

        internal static string InspectSectionProfSkills
        {
            get
            {
                return ResourceManager.GetString("InspectSectionProfSkills", resourceCulture);
            }
        }

        internal static string InspectSectionProgression
        {
            get
            {
                return ResourceManager.GetString("InspectSectionProgression", resourceCulture);
            }
        }

        internal static string InspectSectionSkills
        {
            get
            {
                return ResourceManager.GetString("InspectSectionSkills", resourceCulture);
            }
        }

        internal static string InspectValueFemale
        {
            get
            {
                return ResourceManager.GetString("InspectValueFemale", resourceCulture);
            }
        }

        internal static string InspectValueMale
        {
            get
            {
                return ResourceManager.GetString("InspectValueMale", resourceCulture);
            }
        }

        internal static string InspectValueNo
        {
            get
            {
                return ResourceManager.GetString("InspectValueNo", resourceCulture);
            }
        }

        internal static string InspectValueYes
        {
            get
            {
                return ResourceManager.GetString("InspectValueYes", resourceCulture);
            }
        }

        internal static string InspectLabelExperience
        {
            get
            {
                return ResourceManager.GetString("InspectLabelExperience", resourceCulture);
            }
        }

        internal static string InspectLabelExperienceMax
        {
            get
            {
                return ResourceManager.GetString("InspectLabelExperienceMax", resourceCulture);
            }
        }

        internal static string InspectLabelGold
        {
            get
            {
                return ResourceManager.GetString("InspectLabelGold", resourceCulture);
            }
        }

        internal static string InspectLabelMoney
        {
            get
            {
                return ResourceManager.GetString("InspectLabelMoney", resourceCulture);
            }
        }

        internal static string InspectLabelStrength
        {
            get
            {
                return ResourceManager.GetString("InspectLabelStrength", resourceCulture);
            }
        }

        internal static string InspectLabelIntelligence
        {
            get
            {
                return ResourceManager.GetString("InspectLabelIntelligence", resourceCulture);
            }
        }

        internal static string InspectLabelSkillExperience
        {
            get
            {
                return ResourceManager.GetString("InspectLabelSkillExperience", resourceCulture);
            }
        }

        internal static string InspectLabelBoostProgress
        {
            get
            {
                return ResourceManager.GetString("InspectLabelBoostProgress", resourceCulture);
            }
        }

        internal static string InspectObservationClientData
        {
            get
            {
                return ResourceManager.GetString("InspectObservationClientData", resourceCulture);
            }
        }

        internal static string InspectObservationVisiblePlayers
        {
            get
            {
                return ResourceManager.GetString("InspectObservationVisiblePlayers", resourceCulture);
            }
        }

        internal static string InspectObservationLocalizedNames
        {
            get
            {
                return ResourceManager.GetString("InspectObservationLocalizedNames", resourceCulture);
            }
        }
    }
}
