//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTerraBot.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WildTerraBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Player local não disponível..
        /// </summary>
        internal static string InspectErrorLocalPlayerUnavailable {
            get {
                return ResourceManager.GetString("InspectErrorLocalPlayerUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mais de um player corresponde ao nome informado.
        /// </summary>
        internal static string InspectErrorMultiplePlayersMatch {
            get {
                return ResourceManager.GetString("InspectErrorMultiplePlayersMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum player próximo/visível foi encontrado para inspeção..
        /// </summary>
        internal static string InspectErrorNoNearbyPlayers {
            get {
                return ResourceManager.GetString("InspectErrorNoNearbyPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome do player não informado..
        /// </summary>
        internal static string InspectErrorPlayerNameMissing {
            get {
                return ResourceManager.GetString("InspectErrorPlayerNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Player &apos;{0}&apos; não encontrado entre os players próximos/visíveis..
        /// </summary>
        internal static string InspectErrorPlayerNotFoundFormat {
            get {
                return ResourceManager.GetString("InspectErrorPlayerNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Montaria ativa.
        /// </summary>
        internal static string InspectLabelActiveMount {
            get {
                return ResourceManager.GetString("InspectLabelActiveMount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pet ativo.
        /// </summary>
        internal static string InspectLabelActivePet {
            get {
                return ResourceManager.GetString("InspectLabelActivePet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Avatar.
        /// </summary>
        internal static string InspectLabelAvatar {
            get {
                return ResourceManager.GetString("InspectLabelAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boost Ativo.
        /// </summary>
        internal static string InspectLabelBoostActive {
            get {
                return ResourceManager.GetString("InspectLabelBoostActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boost Atual.
        /// </summary>
        internal static string InspectLabelBoostCurrent {
            get {
                return ResourceManager.GetString("InspectLabelBoostCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Boost Max.
        /// </summary>
        internal static string InspectLabelBoostMax {
            get {
                return ResourceManager.GetString("InspectLabelBoostMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Progresso do Boost.
        /// </summary>
        internal static string InspectLabelBoostProgress {
            get {
                return ResourceManager.GetString("InspectLabelBoostProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Borda.
        /// </summary>
        internal static string InspectLabelBorder {
            get {
                return ResourceManager.GetString("InspectLabelBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cast.
        /// </summary>
        internal static string InspectLabelCast {
            get {
                return ResourceManager.GetString("InspectLabelCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CD.
        /// </summary>
        internal static string InspectLabelCooldown {
            get {
                return ResourceManager.GetString("InspectLabelCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Skill atual.
        /// </summary>
        internal static string InspectLabelCurrentSkill {
            get {
                return ResourceManager.GetString("InspectLabelCurrentSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Distância.
        /// </summary>
        internal static string InspectLabelDistance {
            get {
                return ResourceManager.GetString("InspectLabelDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Durabilidade.
        /// </summary>
        internal static string InspectLabelDurability {
            get {
                return ResourceManager.GetString("InspectLabelDurability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Encantamento.
        /// </summary>
        internal static string InspectLabelEnchantment {
            get {
                return ResourceManager.GetString("InspectLabelEnchantment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Efeito Encant..
        /// </summary>
        internal static string InspectLabelEnchantmentEffect {
            get {
                return ResourceManager.GetString("InspectLabelEnchantmentEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Experiência.
        /// </summary>
        internal static string InspectLabelExperience {
            get {
                return ResourceManager.GetString("InspectLabelExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Experiência Máxima.
        /// </summary>
        internal static string InspectLabelExperienceMax {
            get {
                return ResourceManager.GetString("InspectLabelExperienceMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valores extras.
        /// </summary>
        internal static string InspectLabelExtraValues {
            get {
                return ResourceManager.GetString("InspectLabelExtraValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerado em.
        /// </summary>
        internal static string InspectLabelGeneratedAt {
            get {
                return ResourceManager.GetString("InspectLabelGeneratedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ouro.
        /// </summary>
        internal static string InspectLabelGold {
            get {
                return ResourceManager.GetString("InspectLabelGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Guild.
        /// </summary>
        internal static string InspectLabelGuild {
            get {
                return ResourceManager.GetString("InspectLabelGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HP.
        /// </summary>
        internal static string InspectLabelHp {
            get {
                return ResourceManager.GetString("InspectLabelHp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inteligência.
        /// </summary>
        internal static string InspectLabelIntelligence {
            get {
                return ResourceManager.GetString("InspectLabelIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Level.
        /// </summary>
        internal static string InspectLabelLevel {
            get {
                return ResourceManager.GetString("InspectLabelLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Level.
        /// </summary>
        internal static string InspectLabelLevelInline {
            get {
                return ResourceManager.GetString("InspectLabelLevelInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dinheiro.
        /// </summary>
        internal static string InspectLabelMoney {
            get {
                return ResourceManager.GetString("InspectLabelMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string InspectLabelName {
            get {
                return ResourceManager.GetString("InspectLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Player encontrado.
        /// </summary>
        internal static string InspectLabelPlayerFound {
            get {
                return ResourceManager.GetString("InspectLabelPlayerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Posição.
        /// </summary>
        internal static string InspectLabelPosition {
            get {
                return ResourceManager.GetString("InspectLabelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ProfSkill.
        /// </summary>
        internal static string InspectLabelProfSkill {
            get {
                return ResourceManager.GetString("InspectLabelProfSkill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Qualidade.
        /// </summary>
        internal static string InspectLabelQuality {
            get {
                return ResourceManager.GetString("InspectLabelQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consulta.
        /// </summary>
        internal static string InspectLabelQuery {
            get {
                return ResourceManager.GetString("InspectLabelQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Raridade.
        /// </summary>
        internal static string InspectLabelRarity {
            get {
                return ResourceManager.GetString("InspectLabelRarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Restante.
        /// </summary>
        internal static string InspectLabelRemainingTime {
            get {
                return ResourceManager.GetString("InspectLabelRemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ReqProfLevel.
        /// </summary>
        internal static string InspectLabelReqProfLevel {
            get {
                return ResourceManager.GetString("InspectLabelReqProfLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sexo.
        /// </summary>
        internal static string InspectLabelSex {
            get {
                return ResourceManager.GetString("InspectLabelSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Experiência de Skill.
        /// </summary>
        internal static string InspectLabelSkillExperience {
            get {
                return ResourceManager.GetString("InspectLabelSkillExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Slot.
        /// </summary>
        internal static string InspectLabelSlot {
            get {
                return ResourceManager.GetString("InspectLabelSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SP.
        /// </summary>
        internal static string InspectLabelSp {
            get {
                return ResourceManager.GetString("InspectLabelSp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado.
        /// </summary>
        internal static string InspectLabelState {
            get {
                return ResourceManager.GetString("InspectLabelState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Força.
        /// </summary>
        internal static string InspectLabelStrength {
            get {
                return ResourceManager.GetString("InspectLabelStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título (localizado).
        /// </summary>
        internal static string InspectLabelTitleLocalized {
            get {
                return ResourceManager.GetString("InspectLabelTitleLocalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Título (raw).
        /// </summary>
        internal static string InspectLabelTitleRaw {
            get {
                return ResourceManager.GetString("InspectLabelTitleRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a XP.
        /// </summary>
        internal static string InspectLabelXpInline {
            get {
                return ResourceManager.GetString("InspectLabelXpInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Progresso de XP.
        /// </summary>
        internal static string InspectLabelXpProgress {
            get {
                return ResourceManager.GetString("InspectLabelXpProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem buffs ativos..
        /// </summary>
        internal static string InspectNoBuffsData {
            get {
                return ResourceManager.GetString("InspectNoBuffsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem dados de cosméticos..
        /// </summary>
        internal static string InspectNoCosmeticsData {
            get {
                return ResourceManager.GetString("InspectNoCosmeticsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem dados de equipamento..
        /// </summary>
        internal static string InspectNoEquipmentData {
            get {
                return ResourceManager.GetString("InspectNoEquipmentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem dados de profSkills..
        /// </summary>
        internal static string InspectNoProfSkillsData {
            get {
                return ResourceManager.GetString("InspectNoProfSkillsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sem dados de skills..
        /// </summary>
        internal static string InspectNoSkillsData {
            get {
                return ResourceManager.GetString("InspectNoSkillsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os dados dependem do que o cliente recebeu do servidor..
        /// </summary>
        internal static string InspectObservationClientData {
            get {
                return ResourceManager.GetString("InspectObservationClientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os nomes localizados dependem da tradução ativa no cliente do jogo..
        /// </summary>
        internal static string InspectObservationLocalizedNames {
            get {
                return ResourceManager.GetString("InspectObservationLocalizedNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Skills ativas não expõem um level numérico próprio no struct Skill..
        /// </summary>
        internal static string InspectObservationSkillLevelUnavailable {
            get {
                return ResourceManager.GetString("InspectObservationSkillLevelUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A inspeção é limitada a players próximos/visíveis no cliente..
        /// </summary>
        internal static string InspectObservationVisiblePlayers {
            get {
                return ResourceManager.GetString("InspectObservationVisiblePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSPEÇÃO DE PLAYER.
        /// </summary>
        internal static string InspectReportTitle {
            get {
                return ResourceManager.GetString("InspectReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [ATRIBUTOS].
        /// </summary>
        internal static string InspectSectionAttributes {
            get {
                return ResourceManager.GetString("InspectSectionAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [BUFFS].
        /// </summary>
        internal static string InspectSectionBuffs {
            get {
                return ResourceManager.GetString("InspectSectionBuffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [COSMÉTICOS].
        /// </summary>
        internal static string InspectSectionCosmetics {
            get {
                return ResourceManager.GetString("InspectSectionCosmetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [ECONOMIA].
        /// </summary>
        internal static string InspectSectionEconomy {
            get {
                return ResourceManager.GetString("InspectSectionEconomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [EQUIPAMENTOS].
        /// </summary>
        internal static string InspectSectionEquipment {
            get {
                return ResourceManager.GetString("InspectSectionEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [GERAL].
        /// </summary>
        internal static string InspectSectionGeneral {
            get {
                return ResourceManager.GetString("InspectSectionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [OBSERVAÇÕES].
        /// </summary>
        internal static string InspectSectionObservations {
            get {
                return ResourceManager.GetString("InspectSectionObservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PROF_SKILLS].
        /// </summary>
        internal static string InspectSectionProfSkills {
            get {
                return ResourceManager.GetString("InspectSectionProfSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [PROGRESSÃO].
        /// </summary>
        internal static string InspectSectionProgression {
            get {
                return ResourceManager.GetString("InspectSectionProgression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [SKILLS].
        /// </summary>
        internal static string InspectSectionSkills {
            get {
                return ResourceManager.GetString("InspectSectionSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [vazio].
        /// </summary>
        internal static string InspectValueEmpty {
            get {
                return ResourceManager.GetString("InspectValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feminino.
        /// </summary>
        internal static string InspectValueFemale {
            get {
                return ResourceManager.GetString("InspectValueFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Masculino.
        /// </summary>
        internal static string InspectValueMale {
            get {
                return ResourceManager.GetString("InspectValueMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        internal static string InspectValueNo {
            get {
                return ResourceManager.GetString("InspectValueNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        internal static string InspectValueYes {
            get {
                return ResourceManager.GetString("InspectValueYes", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] HealTraining ENABLED mode={0}.
        /// </summary>
        internal static string HealTrainingEnabledFormat {
            get {
                return ResourceManager.GetString("HealTrainingEnabledFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] HealTraining DISABLED.
        /// </summary>
        internal static string HealTrainingDisabled {
            get {
                return ResourceManager.GetString("HealTrainingDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] Follow Heal: HP baixo, mas a lista de itens de autocura está vazia.
        /// </summary>
        internal static string HealTrainingSelfRecoveryListEmpty {
            get {
                return ResourceManager.GetString("HealTrainingSelfRecoveryListEmpty", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] self recovery use {0} idx={1} hp={2:F0}%.
        /// </summary>
        internal static string HealTrainingSelfRecoveryUseFormat {
            get {
                return ResourceManager.GetString("HealTrainingSelfRecoveryUseFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] self recovery error item='{0}' idx={1} ex={2}:{3}.
        /// </summary>
        internal static string HealTrainingSelfRecoveryErrorFormat {
            get {
                return ResourceManager.GetString("HealTrainingSelfRecoveryErrorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] Follow Heal: HP={0:F0}% abaixo do seguro, mas nenhum item configurado foi encontrado no inventário.
        /// </summary>
        internal static string HealTrainingSelfRecoveryItemMissingFormat {
            get {
                return ResourceManager.GetString("HealTrainingSelfRecoveryItemMissingFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] follow move target='{0}' dist={1:F1} desired={2:F1}.
        /// </summary>
        internal static string HealTrainingFollowMoveFormat {
            get {
                return ResourceManager.GetString("HealTrainingFollowMoveFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] follow mount sync target='{0}' action={1}.
        /// </summary>
        internal static string HealTrainingMountSyncFormat {
            get {
                return ResourceManager.GetString("HealTrainingMountSyncFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] follow mount sync error target='{0}' ex={1}:{2}.
        /// </summary>
        internal static string HealTrainingMountSyncErrorFormat {
            get {
                return ResourceManager.GetString("HealTrainingMountSyncErrorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a [CURA] anti-afk step target='{0}' angle={1:F0} dist={2:F1}.
        /// </summary>
        internal static string HealTrainingAntiAfkStepFormat {
            get {
                return ResourceManager.GetString("HealTrainingAntiAfkStepFormat", resourceCulture);
            }
        }

        internal static string TrainingModeEnabledFormat {
            get {
                return ResourceManager.GetString("TrainingModeEnabledFormat", resourceCulture);
            }
        }

        internal static string TrainingModeDisabled {
            get {
                return ResourceManager.GetString("TrainingModeDisabled", resourceCulture);
            }
        }

        internal static string TrainingModeWaitingDismount {
            get {
                return ResourceManager.GetString("TrainingModeWaitingDismount", resourceCulture);
            }
        }

        internal static string TrainingModeRecoveryUseFormat {
            get {
                return ResourceManager.GetString("TrainingModeRecoveryUseFormat", resourceCulture);
            }
        }

        internal static string TrainingModeRecoveryErrorFormat {
            get {
                return ResourceManager.GetString("TrainingModeRecoveryErrorFormat", resourceCulture);
            }
        }

        internal static string TrainingModeBuffUseFormat {
            get {
                return ResourceManager.GetString("TrainingModeBuffUseFormat", resourceCulture);
            }
        }

        internal static string TrainingModeBuffErrorFormat {
            get {
                return ResourceManager.GetString("TrainingModeBuffErrorFormat", resourceCulture);
            }
        }

        internal static string TrainingModeSkillTryFormat {
            get {
                return ResourceManager.GetString("TrainingModeSkillTryFormat", resourceCulture);
            }
        }

        internal static string TrainingModeSkillErrorFormat {
            get {
                return ResourceManager.GetString("TrainingModeSkillErrorFormat", resourceCulture);
            }
        }

        internal static string TrainingModeAutoAttackWaitingTargetFormat {
            get {
                return ResourceManager.GetString("TrainingModeAutoAttackWaitingTargetFormat", resourceCulture);
            }
        }

        internal static string TrainingModeAutoAttackErrorFormat {
            get {
                return ResourceManager.GetString("TrainingModeAutoAttackErrorFormat", resourceCulture);
            }
        }

        internal static string TamingEnabledFormat {
            get {
                return ResourceManager.GetString("TamingEnabledFormat", resourceCulture);
            }
        }

        internal static string TamingDisabled {
            get {
                return ResourceManager.GetString("TamingDisabled", resourceCulture);
            }
        }

        internal static string TamingAbortFormat {
            get {
                return ResourceManager.GetString("TamingAbortFormat", resourceCulture);
            }
        }

        internal static string TamingDefensePauseFormat {
            get {
                return ResourceManager.GetString("TamingDefensePauseFormat", resourceCulture);
            }
        }

        internal static string TamingDefenseResumeInvalidTarget {
            get {
                return ResourceManager.GetString("TamingDefenseResumeInvalidTarget", resourceCulture);
            }
        }

        internal static string TamingDefenseResumeApproachCatchFormat {
            get {
                return ResourceManager.GetString("TamingDefenseResumeApproachCatchFormat", resourceCulture);
            }
        }

        internal static string TamingDefenseResumeApproachTrapRangeFleeFormat {
            get {
                return ResourceManager.GetString("TamingDefenseResumeApproachTrapRangeFleeFormat", resourceCulture);
            }
        }

        internal static string TamingDefenseResumeEquipCombatWeaponFormat {
            get {
                return ResourceManager.GetString("TamingDefenseResumeEquipCombatWeaponFormat", resourceCulture);
            }
        }

        internal static string TamingDefenseResumeApproachTrapRangeFormat {
            get {
                return ResourceManager.GetString("TamingDefenseResumeApproachTrapRangeFormat", resourceCulture);
            }
        }

        internal static string TamingModeNotImplementedFormat {
            get {
                return ResourceManager.GetString("TamingModeNotImplementedFormat", resourceCulture);
            }
        }

        internal static string TamingTargetLockedFormat {
            get {
                return ResourceManager.GetString("TamingTargetLockedFormat", resourceCulture);
            }
        }

        internal static string TamingAggroTriggerFormat {
            get {
                return ResourceManager.GetString("TamingAggroTriggerFormat", resourceCulture);
            }
        }

        internal static string TamingAggroCombatWeaponEquippedFormat {
            get {
                return ResourceManager.GetString("TamingAggroCombatWeaponEquippedFormat", resourceCulture);
            }
        }

        internal static string TamingAggroEquipCombatWeaponFormat {
            get {
                return ResourceManager.GetString("TamingAggroEquipCombatWeaponFormat", resourceCulture);
            }
        }

        internal static string TamingAggroApproachingCombatFormat {
            get {
                return ResourceManager.GetString("TamingAggroApproachingCombatFormat", resourceCulture);
            }
        }

        internal static string TamingAggroEnteredCombatRangeFormat {
            get {
                return ResourceManager.GetString("TamingAggroEnteredCombatRangeFormat", resourceCulture);
            }
        }

        internal static string TamingAggroFleeConfirmedDuringAttack {
            get {
                return ResourceManager.GetString("TamingAggroFleeConfirmedDuringAttack", resourceCulture);
            }
        }

        internal static string TamingAggroTimeoutForcingFlee {
            get {
                return ResourceManager.GetString("TamingAggroTimeoutForcingFlee", resourceCulture);
            }
        }

        internal static string TamingAggroEnteringWatchFleeFormat {
            get {
                return ResourceManager.GetString("TamingAggroEnteringWatchFleeFormat", resourceCulture);
            }
        }

        internal static string TamingAggroDismountingToAttack {
            get {
                return ResourceManager.GetString("TamingAggroDismountingToAttack", resourceCulture);
            }
        }

        internal static string TamingAggroAttackPulseFormat {
            get {
                return ResourceManager.GetString("TamingAggroAttackPulseFormat", resourceCulture);
            }
        }

        internal static string TamingAggroFleeConfirmed {
            get {
                return ResourceManager.GetString("TamingAggroFleeConfirmed", resourceCulture);
            }
        }

        internal static string TamingAggroDismountingWatchFlee {
            get {
                return ResourceManager.GetString("TamingAggroDismountingWatchFlee", resourceCulture);
            }
        }

        internal static string TamingAggroWatchFleeExpiredFormat {
            get {
                return ResourceManager.GetString("TamingAggroWatchFleeExpiredFormat", resourceCulture);
            }
        }

        internal static string TamingAggroTargetDidNotFleeFormat {
            get {
                return ResourceManager.GetString("TamingAggroTargetDidNotFleeFormat", resourceCulture);
            }
        }

        internal static string TamingAggroWatchFleeStatusFormat {
            get {
                return ResourceManager.GetString("TamingAggroWatchFleeStatusFormat", resourceCulture);
            }
        }

        internal static string TamingAggroSwitchToTrapPipelineFormat {
            get {
                return ResourceManager.GetString("TamingAggroSwitchToTrapPipelineFormat", resourceCulture);
            }
        }

        internal static string TamingTimeoutApproachingTrap {
            get {
                return ResourceManager.GetString("TamingTimeoutApproachingTrap", resourceCulture);
            }
        }

        internal static string TamingApproachingTrapFormat {
            get {
                return ResourceManager.GetString("TamingApproachingTrapFormat", resourceCulture);
            }
        }

        internal static string TamingEnteredTrapRangeFormat {
            get {
                return ResourceManager.GetString("TamingEnteredTrapRangeFormat", resourceCulture);
            }
        }

        internal static string TamingDismountedEquippingTrap {
            get {
                return ResourceManager.GetString("TamingDismountedEquippingTrap", resourceCulture);
            }
        }

        internal static string TamingTimeoutDismounting {
            get {
                return ResourceManager.GetString("TamingTimeoutDismounting", resourceCulture);
            }
        }

        internal static string TamingDismounting {
            get {
                return ResourceManager.GetString("TamingDismounting", resourceCulture);
            }
        }

        internal static string TamingTimeoutEquippingTrap {
            get {
                return ResourceManager.GetString("TamingTimeoutEquippingTrap", resourceCulture);
            }
        }

        internal static string TamingTrapEquippedFormat {
            get {
                return ResourceManager.GetString("TamingTrapEquippedFormat", resourceCulture);
            }
        }

        internal static string TamingEquipTrapFormat {
            get {
                return ResourceManager.GetString("TamingEquipTrapFormat", resourceCulture);
            }
        }

        internal static string TamingTrapEquippedAfterEquipFormat {
            get {
                return ResourceManager.GetString("TamingTrapEquippedAfterEquipFormat", resourceCulture);
            }
        }

        internal static string TamingTimeoutPreparingTrapThrow {
            get {
                return ResourceManager.GetString("TamingTimeoutPreparingTrapThrow", resourceCulture);
            }
        }

        internal static string TamingPreparingTrapThrowFormat {
            get {
                return ResourceManager.GetString("TamingPreparingTrapThrowFormat", resourceCulture);
            }
        }

        internal static string TamingThrowTrapAttemptFormat {
            get {
                return ResourceManager.GetString("TamingThrowTrapAttemptFormat", resourceCulture);
            }
        }

        internal static string TamingTrapConfirmedFormat {
            get {
                return ResourceManager.GetString("TamingTrapConfirmedFormat", resourceCulture);
            }
        }

        internal static string TamingTrapNotConfirmedRetryFormat {
            get {
                return ResourceManager.GetString("TamingTrapNotConfirmedRetryFormat", resourceCulture);
            }
        }

        internal static string TamingTrapNotConfirmedAfterAttemptsFormat {
            get {
                return ResourceManager.GetString("TamingTrapNotConfirmedAfterAttemptsFormat", resourceCulture);
            }
        }

        internal static string TamingTimeoutApproachingCatching {
            get {
                return ResourceManager.GetString("TamingTimeoutApproachingCatching", resourceCulture);
            }
        }

        internal static string TamingTrapEffectGoneBeforeCatchingFormat {
            get {
                return ResourceManager.GetString("TamingTrapEffectGoneBeforeCatchingFormat", resourceCulture);
            }
        }

        internal static string TamingApproachingCatchingFormat {
            get {
                return ResourceManager.GetString("TamingApproachingCatchingFormat", resourceCulture);
            }
        }

        internal static string TamingCatchingSkillNotFound {
            get {
                return ResourceManager.GetString("TamingCatchingSkillNotFound", resourceCulture);
            }
        }

        internal static string TamingTimeoutBeforeCatching {
            get {
                return ResourceManager.GetString("TamingTimeoutBeforeCatching", resourceCulture);
            }
        }

        internal static string TamingCatchingAttemptLimitReachedFormat {
            get {
                return ResourceManager.GetString("TamingCatchingAttemptLimitReachedFormat", resourceCulture);
            }
        }

        internal static string TamingUsingCatchingFormat {
            get {
                return ResourceManager.GetString("TamingUsingCatchingFormat", resourceCulture);
            }
        }

        internal static string TamingTargetInvalidBeforeConfirmation {
            get {
                return ResourceManager.GetString("TamingTargetInvalidBeforeConfirmation", resourceCulture);
            }
        }

        internal static string TamingCombatWeaponNotConfigured {
            get {
                return ResourceManager.GetString("TamingCombatWeaponNotConfigured", resourceCulture);
            }
        }

        internal static string TamingTimeoutEquippingCombatWeapon {
            get {
                return ResourceManager.GetString("TamingTimeoutEquippingCombatWeapon", resourceCulture);
            }
        }

        internal static string TamingTimeoutApproachingCombat {
            get {
                return ResourceManager.GetString("TamingTimeoutApproachingCombat", resourceCulture);
            }
        }

        internal static string TamingPetCapturedFormat {
            get {
                return ResourceManager.GetString("TamingPetCapturedFormat", resourceCulture);
            }
        }

        internal static string TamingTargetRemovedAfterCatchingFormat {
            get {
                return ResourceManager.GetString("TamingTargetRemovedAfterCatchingFormat", resourceCulture);
            }
        }

        internal static string TamingCatchingNotConfirmedRetryFormat {
            get {
                return ResourceManager.GetString("TamingCatchingNotConfirmedRetryFormat", resourceCulture);
            }
        }

        internal static string TamingCatchingNotConfirmedAfterAttemptsFormat {
            get {
                return ResourceManager.GetString("TamingCatchingNotConfirmedAfterAttemptsFormat", resourceCulture);
            }
        }

        internal static string TamingSuccessFormat {
            get {
                return ResourceManager.GetString("TamingSuccessFormat", resourceCulture);
            }
        }

        internal static string TamingFailFormat {
            get {
                return ResourceManager.GetString("TamingFailFormat", resourceCulture);
            }
        }

        internal static string TamingTargetInvalidBeforeFlee {
            get {
                return ResourceManager.GetString("TamingTargetInvalidBeforeFlee", resourceCulture);
            }
        }

        internal static string TamingTargetLost {
            get {
                return ResourceManager.GetString("TamingTargetLost", resourceCulture);
            }
        }

        internal static string UdpRunnerUdpConfiguredFormat {
            get {
                return ResourceManager.GetString("UdpRunnerUdpConfiguredFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerUdpPortErrorFormat {
            get {
                return ResourceManager.GetString("UdpRunnerUdpPortErrorFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerReflectionErrorFormat {
            get {
                return ResourceManager.GetString("UdpRunnerReflectionErrorFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCmdMoveClearingModesFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCmdMoveClearingModesFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCmdMoveToFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCmdMoveToFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCmdHarvestBeforeFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCmdHarvestBeforeFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCmdHarvestIgnoredBusyFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCmdHarvestIgnoredBusyFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestTargetFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestTargetFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCmdHarvestAfterFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCmdHarvestAfterFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHunterTargetFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHunterTargetFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerFishingEnabledFormat {
            get {
                return ResourceManager.GetString("UdpRunnerFishingEnabledFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerFishingDisabled {
            get {
                return ResourceManager.GetString("UdpRunnerFishingDisabled", resourceCulture);
            }
        }

        internal static string UdpRunnerHomeCoordinatesReceivedFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHomeCoordinatesReceivedFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHomeReturningClaimPoint {
            get {
                return ResourceManager.GetString("UdpRunnerHomeReturningClaimPoint", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusListReceivedFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusListReceivedFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCollectListReceivedWithExampleFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCollectListReceivedWithExampleFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCollectListReceivedFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCollectListReceivedFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerTrainingInvalidConfigFormat {
            get {
                return ResourceManager.GetString("UdpRunnerTrainingInvalidConfigFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerResetModesBeforeFormat {
            get {
                return ResourceManager.GetString("UdpRunnerResetModesBeforeFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerResetModesAfterFormat {
            get {
                return ResourceManager.GetString("UdpRunnerResetModesAfterFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerMountStateFormat {
            get {
                return ResourceManager.GetString("UdpRunnerMountStateFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerMounted {
            get {
                return ResourceManager.GetString("UdpRunnerMounted", resourceCulture);
            }
        }

        internal static string UdpRunnerDismounted {
            get {
                return ResourceManager.GetString("UdpRunnerDismounted", resourceCulture);
            }
        }

        internal static string UdpRunnerHomeArrivedPaused {
            get {
                return ResourceManager.GetString("UdpRunnerHomeArrivedPaused", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoMountCheckFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoMountCheckFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoMountSuppressCombatFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoMountSuppressCombatFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerBankTargetFoundFormat {
            get {
                return ResourceManager.GetString("UdpRunnerBankTargetFoundFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerBankChestNotFoundFormat {
            get {
                return ResourceManager.GetString("UdpRunnerBankChestNotFoundFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerBankMovingToChest {
            get {
                return ResourceManager.GetString("UdpRunnerBankMovingToChest", resourceCulture);
            }
        }

        internal static string UdpRunnerBankOpenContainerSkillNotFound {
            get {
                return ResourceManager.GetString("UdpRunnerBankOpenContainerSkillNotFound", resourceCulture);
            }
        }

        internal static string UdpRunnerBankTabsFormat {
            get {
                return ResourceManager.GetString("UdpRunnerBankTabsFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerBankDepositFinished {
            get {
                return ResourceManager.GetString("UdpRunnerBankDepositFinished", resourceCulture);
            }
        }

        internal static string UdpRunnerFishingWaitingRod {
            get {
                return ResourceManager.GetString("UdpRunnerFishingWaitingRod", resourceCulture);
            }
        }

        internal static string UdpRunnerFishingWaitingBaitFormat {
            get {
                return ResourceManager.GetString("UdpRunnerFishingWaitingBaitFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerFishingCasting {
            get {
                return ResourceManager.GetString("UdpRunnerFishingCasting", resourceCulture);
            }
        }

        internal static string UdpRunnerDebugEquipFormat {
            get {
                return ResourceManager.GetString("UdpRunnerDebugEquipFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerEquipBaitFormat {
            get {
                return ResourceManager.GetString("UdpRunnerEquipBaitFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerFishingBaitNotFoundFormat {
            get {
                return ResourceManager.GetString("UdpRunnerFishingBaitNotFoundFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerEquipRodFormat {
            get {
                return ResourceManager.GetString("UdpRunnerEquipRodFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusConfiguredFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusConfiguredFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusItemNotFoundFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusItemNotFoundFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusNoMonitorableUseEffectsFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusNoMonitorableUseEffectsFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusKeepingFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusKeepingFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusUsingFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusUsingFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusUseFailedFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusUseFailedFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusNoMonitorableEffects {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusNoMonitorableEffects", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusEffectMissingFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusEffectMissingFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusEffectEndingFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusEffectEndingFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusItemNoMonitorableEffects {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusItemNoMonitorableEffects", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusNoActiveEffectByName {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusNoActiveEffectByName", resourceCulture);
            }
        }

        internal static string UdpRunnerAutoEatStatusActiveBuffRemainingFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAutoEatStatusActiveBuffRemainingFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAgentNull {
            get {
                return ResourceManager.GetString("UdpRunnerAgentNull", resourceCulture);
            }
        }

        internal static string UdpRunnerAgentDebugFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAgentDebugFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAgentUnknown {
            get {
                return ResourceManager.GetString("UdpRunnerAgentUnknown", resourceCulture);
            }
        }

        internal static string UdpRunnerAggroMeNull {
            get {
                return ResourceManager.GetString("UdpRunnerAggroMeNull", resourceCulture);
            }
        }

        internal static string UdpRunnerAggroNoneFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAggroNoneFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAggroCandidatesHeaderFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAggroCandidatesHeaderFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerAggroErrorFormat {
            get {
                return ResourceManager.GetString("UdpRunnerAggroErrorFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerDefenseActivatedBotOffFormat {
            get {
                return ResourceManager.GetString("UdpRunnerDefenseActivatedBotOffFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatPickAggressorFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatPickAggressorFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatWarnUpdateInvalidTargetFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatWarnUpdateInvalidTargetFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerFishingPostCombatCorpseIgnoredFormat {
            get {
                return ResourceManager.GetString("UdpRunnerFishingPostCombatCorpseIgnoredFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatSkillToPointExceptionFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatSkillToPointExceptionFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHunterSkinningFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHunterSkinningFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerFishingPostCombatTrySkinningFormat {
            get {
                return ResourceManager.GetString("UdpRunnerFishingPostCombatTrySkinningFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerFishingPostCombatSkinningTimeout {
            get {
                return ResourceManager.GetString("UdpRunnerFishingPostCombatSkinningTimeout", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatTickFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatTickFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatWarnInvalidTargetInLogicFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatWarnInvalidTargetInLogicFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatRetargetSwitchFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatRetargetSwitchFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatDefenseDecisionFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatDefenseDecisionFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatMoveApproachFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatMoveApproachFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatStuckDistanceNotReducingFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatStuckDistanceNotReducingFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatDismountToAttackFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatDismountToAttackFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatAttackSkillFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatAttackSkillFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatPulseWaitingFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatPulseWaitingFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerCombatSetTargetExceptionFormat {
            get {
                return ResourceManager.GetString("UdpRunnerCombatSetTargetExceptionFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestActionFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestActionFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestActionStartMounted {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestActionStartMounted", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestActionStart {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestActionStart", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestAbortTimeoutFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestAbortTimeoutFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestActionMicroAdjustArriveFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestActionMicroAdjustArriveFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestActionFlankArriveFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestActionFlankArriveFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestWatchFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestWatchFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestAbortArmedNearTargetStalledFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestAbortArmedNearTargetStalledFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestActionRetryAfterDismountFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestActionRetryAfterDismountFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestActionNearTargetRetryFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestActionNearTargetRetryFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestAbortLostInteractionNearTargetFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestAbortLostInteractionNearTargetFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestAbortMaxFlankAttemptsFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestAbortMaxFlankAttemptsFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestStuckStartFlankFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestStuckStartFlankFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestFlankNoColliderFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestFlankNoColliderFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestFlankNoGoodPointFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestFlankNoGoodPointFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestFlankChosenFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestFlankChosenFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestStallMicroAdjustFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestStallMicroAdjustFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestActionArmedNearTargetDirectRetryFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestActionArmedNearTargetDirectRetryFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestStallFallbackDirectRetryFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestStallFallbackDirectRetryFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestMicroAdjustNoCandidates {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestMicroAdjustNoCandidates", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestMicroAdjustPointFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestMicroAdjustPointFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestFlankCandidateFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestFlankCandidateFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestFlankNoCandidates {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestFlankNoCandidates", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestFlankBestFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestFlankBestFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestCleanupOrphanLockFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestCleanupOrphanLockFormat", resourceCulture);
            }
        }

        internal static string UdpRunnerHarvestResultFormat {
            get {
                return ResourceManager.GetString("UdpRunnerHarvestResultFormat", resourceCulture);
            }
        }
    }
}
