//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WildTerraBot.Properties
{
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WildTerraBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string InspectLabelGuild
        {
            get
            {
                return ResourceManager.GetString("InspectLabelGuild", resourceCulture);
            }
        }

        internal static string InspectLabelLevel
        {
            get
            {
                return ResourceManager.GetString("InspectLabelLevel", resourceCulture);
            }
        }

        internal static string InspectLabelName
        {
            get
            {
                return ResourceManager.GetString("InspectLabelName", resourceCulture);
            }
        }

        internal static string InspectLabelSex
        {
            get
            {
                return ResourceManager.GetString("InspectLabelSex", resourceCulture);
            }
        }

        internal static string InspectReportTitle
        {
            get
            {
                return ResourceManager.GetString("InspectReportTitle", resourceCulture);
            }
        }

        internal static string InspectSectionCosmetics
        {
            get
            {
                return ResourceManager.GetString("InspectSectionCosmetics", resourceCulture);
            }
        }

        internal static string InspectSectionEquipment
        {
            get
            {
                return ResourceManager.GetString("InspectSectionEquipment", resourceCulture);
            }
        }

        internal static string InspectSectionGeneral
        {
            get
            {
                return ResourceManager.GetString("InspectSectionGeneral", resourceCulture);
            }
        }

        internal static string InspectValueFemale
        {
            get
            {
                return ResourceManager.GetString("InspectValueFemale", resourceCulture);
            }
        }

        internal static string InspectValueMale
        {
            get
            {
                return ResourceManager.GetString("InspectValueMale", resourceCulture);
            }
        }

        internal static string InspectValueNo
        {
            get
            {
                return ResourceManager.GetString("InspectValueNo", resourceCulture);
            }
        }

        internal static string InspectValueYes
        {
            get
            {
                return ResourceManager.GetString("InspectValueYes", resourceCulture);
            }
        }
    }
}
